import { test } from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { readFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");

const TOOL_NAME = "monitor_job_postings";
const ACTOR_ID = "QCfICD9kOPiOdj5iI";
// A small valid call. It never reaches Apify: test/mock-fetch.mjs answers it.
const SAMPLE_ARGS = {"keywords": ["account executive"], "sources": ["jobicy"]};
// Live inputs this tool leaves out on purpose, with the reason. `source_tag`
// is the fleet's internal attribution field and is never offered to a model.
const OMITTED = { source_tag: "internal attribution field" };

// The expected inputs come from the live actor, never from the tool:
// test/fixtures/live-input-schema.json is a verbatim copy of the latest build's
// input schema, regenerated by scripts/sync-input-schema-fixture.mjs.
const fixture = JSON.parse(readFileSync(join(here, "fixtures", "live-input-schema.json"), "utf8"));
const ACTOR_INPUTS = Object.entries(fixture.properties)
  .filter(([k, p]) => p.editor !== "hidden" && !Object.keys(OMITTED).includes(k))
  .map(([k]) => k);
const ACTOR_REQUIRED = (fixture.required ?? []).filter((k) => ACTOR_INPUTS.includes(k));

// Speak MCP over stdio to the built server. Returns the response to request id 2.
function rpc(second, { env = {}, preload = false } = {}) {
  return new Promise((resolve, reject) => {
    const childEnv = { ...process.env, ...env };
    if (!("APIFY_TOKEN" in env)) delete childEnv.APIFY_TOKEN;
    const args = preload
      ? ["--import", join(here, "mock-fetch.mjs"), join(repo, "build", "index.js")]
      : [join(repo, "build", "index.js")];
    const child = spawn(process.execPath, args, { stdio: ["pipe", "pipe", "pipe"], env: childEnv });
    let out = "";
    let err = "";
    const timer = setTimeout(() => {
      child.kill();
      reject(new Error(`timed out. stderr: ${err}`));
    }, 30000);
    child.stdout.on("data", (chunk) => {
      out += chunk.toString();
      for (const line of out.split("\n")) {
        if (!line.trim()) continue;
        let msg;
        try {
          msg = JSON.parse(line);
        } catch {
          continue;
        }
        if (msg.id === 2) {
          clearTimeout(timer);
          child.kill();
          resolve(msg);
        }
      }
    });
    child.stderr.on("data", (chunk) => {
      err += chunk.toString();
    });
    child.on("error", reject);
    const send = (m) => child.stdin.write(JSON.stringify(m) + "\n");
    send({ jsonrpc: "2.0", id: 1, method: "initialize", params: { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "wrapper-test", version: "0.0.0" } } });
    send({ jsonrpc: "2.0", method: "notifications/initialized" });
    send({ jsonrpc: "2.0", id: 2, ...second });
  });
}

const listTools = async () => (await rpc({ method: "tools/list", params: {} })).result;
const callTool = (env) =>
  rpc({ method: "tools/call", params: { name: TOOL_NAME, arguments: SAMPLE_ARGS } }, { env, preload: true });

test("serves tools/list with no APIFY_TOKEN set", async () => {
  const result = await listTools();
  assert.equal(result.tools.length, 1);
  assert.equal(result.tools[0].name, TOOL_NAME);
  assert.ok(result.tools[0].description.length > 0);
});

test("tool schema exposes every live actor input", async () => {
  const result = await listTools();
  const props = Object.keys(result.tools[0].inputSchema.properties).sort();
  assert.deepEqual(props, [...ACTOR_INPUTS].sort());
});

test("tool schema requires exactly what the live actor requires", async () => {
  const result = await listTools();
  const required = (result.tools[0].inputSchema.required ?? []).slice().sort();
  assert.deepEqual(required, [...ACTOR_REQUIRED].sort());
});

test("enum inputs offer exactly the live actor's values", async () => {
  const result = await listTools();
  const props = result.tools[0].inputSchema.properties;
  for (const [key, p] of Object.entries(props)) {
    const live = fixture.properties[key];
    if (!live) continue;
    if (p.enum && live.enum) assert.deepEqual(p.enum.map(String).sort(), live.enum.map(String).sort(), key);
    if (p.items?.enum && live.items?.enum) assert.deepEqual(p.items.enum.slice().sort(), live.items.enum.slice().sort(), key);
  }
});

test("the fixture was read from this actor, not a sibling", () => {
  assert.equal(fixture._provenance.actorId, ACTOR_ID);
  assert.ok(ACTOR_INPUTS.length > 0);
});

test("source pins the immutable actor id and never calls run-sync", () => {
  const src = readFileSync(join(repo, "src", "index.ts"), "utf8");
  assert.ok(src.includes(`"${ACTOR_ID}"`), "actor id missing from source");
  // Comments may name the old endpoint to explain why it is gone; code may not.
  const code = src.split("\n").filter((l) => !l.trim().startsWith("//")).join("\n");
  assert.ok(!code.includes("run-sync-get-dataset-items"), "run-sync endpoint still called");
});

test("a call starts the run, polls it, and returns the dataset", async () => {
  const logFile = join(mkdtempSync(join(tmpdir(), "wrapper-")), "fetch.log");
  const msg = await callTool({ APIFY_TOKEN: "test-token", MOCK_FETCH_LOG: logFile });
  assert.ok(!msg.result.isError, msg.result.content?.[0]?.text);
  assert.deepEqual(JSON.parse(msg.result.content[0].text), [{ mocked: true, row_status: "ok" }]);
  const calls = readFileSync(logFile, "utf8").trim().split("\n").map((l) => JSON.parse(l));
  assert.equal(calls[0].method, "POST");
  assert.match(calls[0].url, new RegExp(`/v2/acts/${ACTOR_ID}/runs\\?timeout=1800(&|$)`));
  assert.ok(calls.some((c) => c.url.endsWith("/v2/actor-runs/run123")), "never polled the run");
  assert.ok(calls.some((c) => c.url.includes("/v2/datasets/ds123/items")), "never read the dataset");
  assert.ok(!calls.some((c) => c.url.includes("run-sync")), "called run-sync");
});

test("a run that does not succeed is reported as an error, not an empty result", async () => {
  const msg = await callTool({ APIFY_TOKEN: "test-token", MOCK_RUN_STATUS: "FAILED" });
  assert.equal(msg.result.isError, true);
  assert.match(msg.result.content[0].text, /did not succeed .*FAILED/);
});
